spring:
  datasource:
    username: tradenova_app
    password: novaLo048679@!#

tradenova:
  jwt:
    secret: ThisIsASecretKeyForTradeNovaJwtToken1234
    access-token-validity-in-seconds: 3600

kis:
  appkey: PSnBVk1TkpF1adgiBltS39y3R3tYojFjIapj
  appsecret: jsN5KmvKN8LZy/C1evlkOOSnG3w07+feQywkL4mlCOXttI0SSsidVJQaXTA6AmxXBJwsfzWxXu81HkHIPFvQFqcDG4wimOi8V58HGOTo7rDOs/Q8xzwMWF7z2GXGzuBy5NXJZddGnrDuxw7CN75RLymUw2fGu649C22p4Cao/cbWKh01q+c=