spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tradenova?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: tradenova_app
    password: novaLo048679@!#
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update #개발 단계: 엔티티 보고 테이블 자동 생성/수정
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC #DB랑 주고바든 시간은 UTC 기준
    show-sql: true

  sql:
    init:
      mode: never

  jackson:
    time_zone: UTC #JSON 직렬화 기본 타임존

    tradenova:
      jwt:
        sercet: ""
        acces-token-validity-in-seconds : 3600

server:
  port: 8080
