spring:
  profiles:
    active: local

  datasource:
    url: jdbc:mysql://localhost:3306/tradenova?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update #개발 단계: 엔티티 보고 테이블 자동 생성/수정
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC #DB랑 주고바든 시간은 UTC 기준
    show-sql: true

  sql:
    init:
      mode: never

  app:
    dev:
      allow_any_verify-code: true

  jackson:
    time_zone: UTC #JSON 직렬화 기본 타임존

tradenova:
  jwt:
    secret: ${JWT_SECRET}
    access-token-validity-in-seconds : ${JWT_EXPIRE_SECONDS:3600}

kis:
  base-url: https://openapi.koreainvestment.com:9443
  appkey: ${KIS_APPKEY}
  appsecret: ${KIS_APPSECRET}
  custtype: P  # 개인: P, 법인: B

server:
  port: 8080
